name: Build & Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository   # label for the step
        uses: actions/checkout@v3    # prebuilt action: downloads the repository code into the VM

      - name: Set up JDK 17           # label for the step
        uses: actions/setup-java@v3   # prebuilt action: installs Java on the VM
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3  # speeds up builds by caching ~/.m2/repository
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests
        run: mvn -B clean verify
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          TESTCONTAINERS_CHECKS_DISABLE: true
          JWT_SECRET: ${{ secrets.JWT_SECRET }}